### PR TITLE
Update wadl from upstream

### PR DESCRIPTION
**Pull request by jasondunsmore**
Update wadl from upstream to update API documentation with latest
information.

### CODE REVIEW

**Comment by rs-randallburt** [comment]
I'm a bit concerned that several examples seem to be removed. Thoughts?

**Comment by masthalter** [comment]
I agree Randall. We put in a lot of work just to get the examples we have!


Mike

________________________________

**Comment by jasondunsmore** [comment]
Have we diverged from upstream??
https://github.com/rackerlabs/docs-cloud-orchestration/commit/11797a106c1cee6cbced5a34def653323b4d8765#diff-d83c3d41c13f987d182bd3e6a644fe0b

**Comment by rs-randallburt** [comment]
Dunno. Might have to check with @vikomall because I know we do make some modifications to the upstream WADL.

**Comment by jasondunsmore** [comment]
@masthalter Do you want to submit those changes to https://github.com/openstack/api-site/tree/master/api-ref/src/wadls/orchestration-api/src/v1 ?  It doesn't make sense to keep these as downstream-only patches which have to be manually merged in every time we update from upstream.  I didn't see anything Rackspace-specific in there.

**Comment by rs-randallburt** [comment]
@jasondunsmore that was a concious descision to make modifications to upstream (not the examples, though. IIRC, those should go upstream), but there are other changes that we make: remove unsupported endpoints and operations that require administrative user privileges in our cloud.

**Comment by jasondunsmore** [comment]
@rs-randallburt Okay, thanks for the heads-up.

I just went through every commit to wadl/ and here is a list of legit downstream-only commits:

https://github.com/rackerlabs/docs-cloud-orchestration/commit/71965c3d51b1f0304a383a8e25edc5d4aede9ce1
https://github.com/rackerlabs/docs-cloud-orchestration/commit/daf06ed7c34df2ef546d1f6ec682056898e319c2

It will be useful to maintain a list of these to make updating the docs easier.

I must have missed the ones that remove the unsupported endpoints and admin-only endpoints.  Do you know which these are?

Here is a list of commits which contain changes that should be submitted upstream:

https://github.com/rackerlabs/docs-cloud-orchestration/commit/e38a6655d786cf0f2b8bb457d67397fc41ebe0d2
https://github.com/rackerlabs/docs-cloud-orchestration/commit/11797a106c1cee6cbced5a34def653323b4d8765
https://github.com/rackerlabs/docs-cloud-orchestration/commit/ee2e06717ec7376ad59cf8874ca60dd417ac3385
https://github.com/rackerlabs/docs-cloud-orchestration/commit/dd84f1bf2eaced9f3ff09c8e4c467b03f41e4a0d
https://github.com/rackerlabs/docs-cloud-orchestration/commit/7ba5a4031508592c871ba88f30aa9e38d81e21de
https://github.com/rackerlabs/docs-cloud-orchestration/commit/93af45539c730292f9c7be3f31a0ef927c35c117
https://github.com/rackerlabs/docs-cloud-orchestration/commit/bd8f9441c8afdb18264d1c8aead2a6f219b73963
https://github.com/rackerlabs/docs-cloud-orchestration/commit/14e514211392c4d406f7a79485d9db294097b396
https://github.com/rackerlabs/docs-cloud-orchestration/commit/249fb21558314551f1e695929185bc6af5a7aeac#diff-d83c3d41c13f987d182bd3e6a644fe0b
https://github.com/rackerlabs/docs-cloud-orchestration/commit/0c4240008b3d0c8c088cccae1709bb35adacda0e

**Comment by rs-randallburt** [comment]
Not offhand. Will need to check with @vikomall since he did most, if not all, of that work.

**Comment by vikomall** [comment]
@rs-randallburt  @jasondunsmore  IIRC, there is no special reason to keep those examples related commits internal. I did those changes to fix our documentation, but never got a chance (or probably forgot) to submit upstream.

**Comment by jasondunsmore** [comment]
@masthalter Would you like to submit those changes upstream?  I can do it if you're busy.  Just let me know.

**Comment by masthalter** [comment]
Vijendar and Randall,


Do you want Jason to go ahead and submit the changes upstream?


Mike

________________________________

**Comment by vikomall** [comment]
@masthalter  I don't see any reason for not submitting upstream.

**Comment by masthalter** [comment]
Please go ahead and submit your changes upstream Jason!


Thanks!


Mike

________________________________

**Comment by jasondunsmore** [comment]
Working through the list in reverse order...

0c42400
Can be removed in favor of newer upstream changes:
https://github.com/openstack/api-site/blob/master/api-ref/src/wadls/orchestration-api/src/v1/orchestration-api.wadl#L1154-L1171
https://github.com/openstack/api-site/blob/master/api-ref/src/wadls/orchestration-api/src/v1/samples/stack_abandon.json

Submitted upstream:
https://github.com/rackerlabs/docs-cloud-orchestration/commit/0c4240008b3d0c8c088cccae1709bb35adacda0e#diff-877c6c4306a494eb0edbc179689ab4aa
https://review.openstack.org/#/c/194398/

**Comment by jasondunsmore** [comment]
Finished going through 249fb21

Submitted upstream
https://review.openstack.org/#/c/200736/
https://review.openstack.org/#/c/200717/

Keeping downstream
https://github.com/rackerlabs/api-site/tree/rs-heat-dollar-vars

**Comment by jasondunsmore** [comment]
Finished going through 068b8a844

Submitted upstream
https://review.openstack.org/#/c/201775/
https://review.openstack.org/#/c/201713/
https://review.openstack.org/#/c/201783/
https://review.openstack.org/#/c/202154/
https://review.openstack.org/#/c/202149/
https://review.openstack.org/#/c/201680/
https://review.openstack.org/#/c/201350/

Keeping downstream
https://github.com/rackerlabs/api-site/tree/rs-heat-rm-resource-metadata

**Comment by jasondunsmore** [comment]
Finished 14e5142113

Submitted upstream
https://review.openstack.org/#/c/202246/

**Comment by jasondunsmore** [comment]
Finished bd8f9441c8

No changes

**Comment by jasondunsmore** [comment]
Finished 93af45539

Submitted upstream
https://review.openstack.org/#/c/202276/

Updated
https://github.com/rackerlabs/api-site/tree/rs-heat-dollar-vars

**Comment by jasondunsmore** [comment]
Finished 7ba5a40315085

Submitted upstream
https://review.openstack.org/#/c/202276/
https://review.openstack.org/#/c/203210/
https://review.openstack.org/#/c/203230/

Updated
https://github.com/rackerlabs/api-site/tree/rs-heat-dollar-vars

**Comment by jasondunsmore** [comment]
Finished dd84f1bf2e

No changes

**Comment by jasondunsmore** [comment]
Finished ee2e06717

Submitted upstream
https://review.openstack.org/#/c/203246/

**Comment by jasondunsmore** [comment]
Finished 11797a106c1ce

No changes

**Comment by jasondunsmore** [comment]
Finished e38a665

No changes

**Comment by jasondunsmore** [comment]
Finished 71965c3 & daf06ed

Keeping downstream
https://github.com/rackerlabs/api-site/tree/rs-heat-flavors-images

**Pull request closed without merging**
